// src/Pages/Components/Icons.tsx
import { PhosphorLogo } from '@phosphor-icons/react';
import {
  SiAdobephotoshop,
  SiBitbucket,
  SiConfluence,
  SiElementor,
  SiExpress,
  SiFigma,
  SiFrontendmentor,
  SiGit,
  SiGithub,
  SiJavascript,
  SiJirasoftware,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPhp,
  SiReact,
  SiStyledcomponents,
  SiTailwindcss,
  SiThreedotjs,
  SiTypescript,
  SiVercel,
  SiVite,
  SiWoocommerce,
  SiWordpress,
} from 'react-icons/si';

export const technologyIcons: Record<string, React.ReactNode> = {
  Vercel: <SiVercel />,
  React: <SiReact />,
  TypeScript: <SiTypescript />,
  StyledComponents: <SiStyledcomponents />,
  FrontendMentor: <SiFrontendmentor />,
  Vite: <SiVite />,
  NodeJS: <SiNodedotjs />,
  Phosphor: <PhosphorLogo />,
  Github: <SiGithub />,
  MongoDB: <SiMongodb />,
  Express: <SiExpress />,
  Tailwindcss: <SiTailwindcss />,
  Javascript: <SiJavascript />,
  Git: <SiGit />,
  ThreeJS: <SiThreedotjs />,
  NextJS: <SiNextdotjs />,
  Jira: <SiJirasoftware />,
  BitBucket: <SiBitbucket />,
  PHP: <SiPhp />,
  WordPress: <SiWordpress />,
  Elementor: <SiElementor />,
  WooCommerce: <SiWoocommerce />,
  Photoshop: <SiAdobephotoshop />,
  Figma: <SiFigma />,
  Confluence: <SiConfluence />,
  MySQL: <SiMysql />,
};
